import { Team } from './types'

export const TEAMS: Team[] = [
  { g:'A', flag:'🇲🇽', name:'Mexico', abbr:'MEX', conf:'CONCACAF',
    auth:{ drink:'Mezcal', desc:'Smoky agave spirit — sip it like you mean it', wiki:'https://en.wikipedia.org/wiki/Mezcal' },
    usa:{ drink:'Tequila Shot', desc:'Patron, Casamigos, or whatever well tequila is back there', wiki:'https://en.wikipedia.org/wiki/Tequila' } },
  { g:'A', flag:'🇿🇦', name:'South Africa', abbr:'RSA', conf:'CAF',
    auth:{ drink:'Amarula', desc:'Cream liqueur made from marula fruit', wiki:'https://en.wikipedia.org/wiki/Amarula' },
    usa:{ drink:'Baileys Shot', desc:"Closest cream liqueur you'll find — close enough", wiki:'https://en.wikipedia.org/wiki/Baileys_Irish_Cream' } },
  { g:'A', flag:'🇰🇷', name:'South Korea', abbr:'KOR', conf:'AFC',
    auth:{ drink:'Soju', desc:"Korea's beloved rice spirit, deceptively smooth", wiki:'https://en.wikipedia.org/wiki/Soju' },
    usa:{ drink:'Soju', desc:'Actually everywhere now — H Mart, Total Wine, most liquor stores', wiki:'https://en.wikipedia.org/wiki/Soju' } },
  { g:'A', flag:'🇨🇿', name:'Czechia', abbr:'CZE', conf:'UEFA',
    auth:{ drink:'Becherovka', desc:'Herbal bitters from Karlovy Vary', wiki:'https://en.wikipedia.org/wiki/Becherovka' },
    usa:{ drink:'Jägermeister', desc:'Both are herbal digestifs — Jager is just easier to find', wiki:'https://en.wikipedia.org/wiki/J%C3%A4germeister' } },
  { g:'B', flag:'🇨🇭', name:'Switzerland', abbr:'SUI', conf:'UEFA',
    auth:{ drink:'Kirsch', desc:'Clear cherry brandy from the Alps', wiki:'https://en.wikipedia.org/wiki/Kirschwasser' },
    usa:{ drink:'Cherry Vodka Shot', desc:'Smirnoff Cherry or Absolut — close enough vibes', wiki:'https://en.wikipedia.org/wiki/Vodka' } },
  { g:'B', flag:'🇨🇦', name:'Canada', abbr:'CAN', conf:'CONCACAF',
    auth:{ drink:'Canadian Whisky', desc:'Smooth rye whisky — Crown Royal or bust', wiki:'https://en.wikipedia.org/wiki/Canadian_whisky' },
    usa:{ drink:'Crown Royal', desc:'Crown Royal is literally everywhere — no sub needed', wiki:'https://en.wikipedia.org/wiki/Crown_Royal' } },
  { g:'B', flag:'🇶🇦', name:'Qatar', abbr:'QAT', conf:'AFC',
    auth:{ drink:'Arak', desc:'Anise-flavored spirit, goes cloudy with water', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:'Italian anise liqueur — same vibe, way more available', wiki:'https://en.wikipedia.org/wiki/Sambuca' } },
  { g:'B', flag:'🇧🇦', name:'Bosnia & Herz.', abbr:'BIH', conf:'UEFA',
    auth:{ drink:'Rakija', desc:'Balkan plum brandy — rough, strong, traditional', wiki:'https://en.wikipedia.org/wiki/Rakija' },
    usa:{ drink:'Slivovitz or Brandy', desc:'Eastern European delis carry it — otherwise any dark brandy', wiki:'https://en.wikipedia.org/wiki/Slivovitz' } },
  { g:'C', flag:'🇧🇷', name:'Brazil', abbr:'BRA', conf:'CONMEBOL',
    auth:{ drink:'Cachaça', desc:'Sugar cane spirit — base of the caipirinha', wiki:'https://en.wikipedia.org/wiki/Cacha%C3%A7a' },
    usa:{ drink:'Cachaça or White Rum', desc:'Leblon at most Total Wine stores — or use white rum', wiki:'https://en.wikipedia.org/wiki/Rum' } },
  { g:'C', flag:'🇲🇦', name:'Morocco', abbr:'MAR', conf:'CAF',
    auth:{ drink:'Mahia', desc:'North African fig brandy, a rare pour', wiki:'https://en.wikipedia.org/wiki/Mahia_(drink)' },
    usa:{ drink:'Brandy Shot', desc:'Fig brandy is impossible to find — sub any fruit brandy', wiki:'https://en.wikipedia.org/wiki/Brandy' } },
  { g:'C', flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', name:'Scotland', abbr:'SCO', conf:'UEFA',
    auth:{ drink:'Scotch Whisky', desc:'Single malt, neat — no ice, no apologies', wiki:'https://en.wikipedia.org/wiki/Scotch_whisky' },
    usa:{ drink:'Scotch Shot', desc:"Dewar's, Johnnie Walker Black, or Monkey Shoulder — at every bar", wiki:'https://en.wikipedia.org/wiki/Scotch_whisky' } },
  { g:'C', flag:'🇨🇩', name:'Congo DR', abbr:'COD', conf:'CAF',
    auth:{ drink:'Lotoko', desc:'Congolese corn spirit — powerful moonshine', wiki:'https://en.wikipedia.org/wiki/Lotoko' },
    usa:{ drink:'Ole Smoky Moonshine', desc:'American moonshine is the closest readily available cousin', wiki:'https://en.wikipedia.org/wiki/Moonshine' } },
  { g:'D', flag:'🇺🇸', name:'USA', abbr:'USA', conf:'CONCACAF',
    auth:{ drink:'Bourbon', desc:'Kentucky straight — America in a glass', wiki:'https://en.wikipedia.org/wiki/Bourbon_whiskey' },
    usa:{ drink:'Bourbon', desc:"You're already home. Maker's Mark, Bulleit, or Jim Beam", wiki:'https://en.wikipedia.org/wiki/Bourbon_whiskey' } },
  { g:'D', flag:'🇦🇺', name:'Australia', abbr:'AUS', conf:'AFC',
    auth:{ drink:'Tim Tam Slam', desc:'Bite both ends, sip hot choc through the cookie', wiki:'https://en.wikipedia.org/wiki/Tim_Tam#Tim_Tam_Slam' },
    usa:{ drink:'Fireball Shot', desc:'Warm, sweet, universally stocked — Aussie bars love Fireball too', wiki:'https://en.wikipedia.org/wiki/Fireball_Cinnamon_Whisky' } },
  { g:'D', flag:'🇹🇷', name:'Turkiye', abbr:'TUR', conf:'UEFA',
    auth:{ drink:'Rakı', desc:"Lion's milk — anise spirit, ice water chaser", wiki:'https://en.wikipedia.org/wiki/Rak%C4%B1' },
    usa:{ drink:'Sambuca', desc:'Italian anise spirit — same character, at every bar', wiki:'https://en.wikipedia.org/wiki/Sambuca' } },
  { g:'D', flag:'🇬🇭', name:'Ghana', abbr:'GHA', conf:'CAF',
    auth:{ drink:'Akpeteshie', desc:'Powerful palm wine distillate from West Africa', wiki:'https://en.wikipedia.org/wiki/Akpeteshie' },
    usa:{ drink:'Overproof Rum Shot', desc:"Gosling's Black Seal or Bacardi 151 — same raw-spirit energy", wiki:'https://en.wikipedia.org/wiki/Overproof_rum' } },
  { g:'E', flag:'🇩🇪', name:'Germany', abbr:'GER', conf:'UEFA',
    auth:{ drink:'Jägermeister', desc:'56-herb digestif — prost!', wiki:'https://en.wikipedia.org/wiki/J%C3%A4germeister' },
    usa:{ drink:'Jägermeister', desc:'No sub needed — Jager is in every single American bar', wiki:'https://en.wikipedia.org/wiki/J%C3%A4germeister' } },
  { g:'E', flag:'🇨🇮', name:'Ivory Coast', abbr:'CIV', conf:'CAF',
    auth:{ drink:'Koutoukou', desc:'Palm wine hooch — fiery West African spirit', wiki:'https://en.wikipedia.org/wiki/Koutoukou' },
    usa:{ drink:'Overproof Rum', desc:'Plantation OFTD or Smith & Cross — funky, fierce, similar energy', wiki:'https://en.wikipedia.org/wiki/Overproof_rum' } },
  { g:'E', flag:'🇪🇨', name:'Ecuador', abbr:'ECU', conf:'CONMEBOL',
    auth:{ drink:'Canelazo', desc:'Warm cinnamon & sugarcane spirit punch', wiki:'https://en.wikipedia.org/wiki/Canelazo' },
    usa:{ drink:'Fireball Shot', desc:'Cinnamon + sugarcane vibes — Fireball is basically Canelazo in a shot', wiki:'https://en.wikipedia.org/wiki/Fireball_Cinnamon_Whisky' } },
  { g:'E', flag:'🇨🇼', name:'Curacao', abbr:'CUW', conf:'CONCACAF',
    auth:{ drink:'Blue Curaçao', desc:"Orange liqueur, impossibly blue — it's their thing", wiki:'https://en.wikipedia.org/wiki/Cura%C3%A7ao_(liqueur)' },
    usa:{ drink:'Blue Curaçao Shot', desc:'DeKuyper Blue Curaçao is literally everywhere — this one is easy', wiki:'https://en.wikipedia.org/wiki/Cura%C3%A7ao_(liqueur)' } },
  { g:'F', flag:'🇳🇱', name:'Netherlands', abbr:'NED', conf:'UEFA',
    auth:{ drink:'Jenever', desc:'Dutch gin ancestor — the original G&T', wiki:'https://en.wikipedia.org/wiki/Jenever' },
    usa:{ drink:'Gin Shot', desc:'Tanqueray or Bombay Sapphire — Dutch and London gin share DNA', wiki:'https://en.wikipedia.org/wiki/Gin' } },
  { g:'F', flag:'🇯🇵', name:'Japan', abbr:'JPN', conf:'AFC',
    auth:{ drink:'Shochu', desc:'Distilled spirit, lighter than sake, more complex', wiki:'https://en.wikipedia.org/wiki/Sh%C5%8Dch%C5%AB' },
    usa:{ drink:'Sake Shot', desc:'More available than shochu — Gekkeikan at most grocery stores', wiki:'https://en.wikipedia.org/wiki/Sake' } },
  { g:'F', flag:'🇸🇪', name:'Sweden', abbr:'SWE', conf:'UEFA',
    auth:{ drink:'Aquavit', desc:'Caraway-spiced Scandinavian spirit, served ice cold', wiki:'https://en.wikipedia.org/wiki/Aquavit' },
    usa:{ drink:'Aquavit', desc:'Linie Aquavit is at most Total Wine — no sub needed', wiki:'https://en.wikipedia.org/wiki/Aquavit' } },
  { g:'F', flag:'🇹🇳', name:'Tunisia', abbr:'TUN', conf:'CAF',
    auth:{ drink:'Boukha', desc:'Fig eau-de-vie from Tunisia — subtle and fragrant', wiki:'https://en.wikipedia.org/wiki/Boukha' },
    usa:{ drink:'Pisco Shot', desc:'Another fruit brandy — aromatic, found at decent liquor stores', wiki:'https://en.wikipedia.org/wiki/Pisco' } },
  { g:'G', flag:'🇧🇪', name:'Belgium', abbr:'BEL', conf:'UEFA',
    auth:{ drink:'Jenever', desc:'Belgian-style genever, the OG gin', wiki:'https://en.wikipedia.org/wiki/Jenever' },
    usa:{ drink:'Gin Shot', desc:"Hendrick's or Tanqueray — both carry that botanical jenever DNA", wiki:'https://en.wikipedia.org/wiki/Gin' } },
  { g:'G', flag:'🇮🇷', name:'Iran', abbr:'IRN', conf:'AFC',
    auth:{ drink:'Aragh Sagi', desc:'Traditional Iranian raisin moonshine', wiki:'https://en.wikipedia.org/wiki/Aragh_sagi' },
    usa:{ drink:'Grappa Shot', desc:'Italian grape pomace brandy — closest readily available sub', wiki:'https://en.wikipedia.org/wiki/Grappa' } },
  { g:'G', flag:'🇪🇬', name:'Egypt', abbr:'EGY', conf:'CAF',
    auth:{ drink:'Zibib', desc:'Egyptian anise spirit, cousin of Greek ouzo', wiki:'https://en.wikipedia.org/wiki/Zibib' },
    usa:{ drink:'Ouzo Shot', desc:"Greek ouzo is Zibib's cousin — found at Greek restaurants and Total Wine", wiki:'https://en.wikipedia.org/wiki/Ouzo' } },
  { g:'G', flag:'🇺🇿', name:'Uzbekistan', abbr:'UZB', conf:'AFC',
    auth:{ drink:'Starka Vodka', desc:'Aged rye vodka from Central Asia', wiki:'https://en.wikipedia.org/wiki/Starka' },
    usa:{ drink:'Rye Whiskey Shot', desc:'Bulleit Rye or Rittenhouse — aged grain spirit, same ballpark', wiki:'https://en.wikipedia.org/wiki/Rye_whiskey' } },
  { g:'H', flag:'🇪🇸', name:'Spain', abbr:'ESP', conf:'UEFA',
    auth:{ drink:'Orujo', desc:'Spanish pomace brandy — bold and rustic', wiki:'https://en.wikipedia.org/wiki/Orujo' },
    usa:{ drink:'Grappa Shot', desc:'Italian pomace brandy — same grape-skin base, same rustic kick', wiki:'https://en.wikipedia.org/wiki/Grappa' } },
  { g:'H', flag:'🇺🇾', name:'Uruguay', abbr:'URU', conf:'CONMEBOL',
    auth:{ drink:'Grappamiel', desc:'Honey grappa — sweet, warming, very Uruguayan', wiki:'https://en.wikipedia.org/wiki/Grappamiel' },
    usa:{ drink:'Drambuie Shot', desc:'Honey + spirit liqueur — sweet and warming just like Grappamiel', wiki:'https://en.wikipedia.org/wiki/Drambuie' } },
  { g:'H', flag:'🇨🇻', name:'Cape Verde', abbr:'CPV', conf:'CAF',
    auth:{ drink:'Grogue', desc:'Unaged sugarcane rum, rough and authentic', wiki:'https://en.wikipedia.org/wiki/Grogue_(liquor)' },
    usa:{ drink:'White Rum Shot', desc:'Bacardi Silver or Plantation 3 Star — unaged sugarcane, same idea', wiki:'https://en.wikipedia.org/wiki/Rum' } },
  { g:'H', flag:'🇸🇦', name:'Saudi Arabia', abbr:'KSA', conf:'AFC',
    auth:{ drink:'Arak', desc:'Traditional Middle Eastern anise spirit', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:"Italian anise liqueur — Sambuca is Arak's party cousin", wiki:'https://en.wikipedia.org/wiki/Sambuca' } },
  { g:'I', flag:'🇫🇷', name:'France', abbr:'FRA', conf:'UEFA',
    auth:{ drink:'Cognac', desc:'Aged grape brandy — sophistication in a snifter', wiki:'https://en.wikipedia.org/wiki/Cognac' },
    usa:{ drink:'Hennessy VS Shot', desc:'Henny is in every bar in America — French cognac, no sub needed', wiki:'https://en.wikipedia.org/wiki/Hennessy' } },
  { g:'I', flag:'🇸🇳', name:'Senegal', abbr:'SEN', conf:'CAF',
    auth:{ drink:'Bissap', desc:'Hibiscus liqueur — floral and bittersweet', wiki:'https://en.wikipedia.org/wiki/Bissap' },
    usa:{ drink:'St-Germain Shot', desc:'Elderflower liqueur — floral, slightly sweet, same energy', wiki:'https://en.wikipedia.org/wiki/St-Germain_(liqueur)' } },
  { g:'I', flag:'🇳🇴', name:'Norway', abbr:'NOR', conf:'UEFA',
    auth:{ drink:'Linie Aquavit', desc:'Aged at sea crossing the equator twice — unique', wiki:'https://en.wikipedia.org/wiki/Linie_Aquavit' },
    usa:{ drink:'Aquavit', desc:'Linie is at Total Wine — or use Absolut Dill as a wild card sub', wiki:'https://en.wikipedia.org/wiki/Aquavit' } },
  { g:'I', flag:'🇳🇿', name:'New Zealand', abbr:'NZL', conf:'OFC',
    auth:{ drink:'Manuka Whisky', desc:'Honey-infused whisky with New Zealand botanicals', wiki:'https://en.wikipedia.org/wiki/Whisky_in_New_Zealand' },
    usa:{ drink:'Jack Honey Shot', desc:"Jack Daniel's Tennessee Honey — honey whiskey is everywhere", wiki:'https://en.wikipedia.org/wiki/Jack_Daniel%27s' } },
  { g:'J', flag:'🇦🇷', name:'Argentina', abbr:'ARG', conf:'CONMEBOL',
    auth:{ drink:'Fernet-Branca & Coke', desc:"Bitter herbal liqueur with Coke — Argentina's national cocktail", wiki:'https://en.wikipedia.org/wiki/Fernet' },
    usa:{ drink:'Fernet-Branca Shot', desc:"Actually at most craft bars now — or sub Jager if you can't find it", wiki:'https://en.wikipedia.org/wiki/Fernet-Branca' } },
  { g:'J', flag:'🇦🇹', name:'Austria', abbr:'AUT', conf:'UEFA',
    auth:{ drink:'Stroh Rum', desc:'80% Austrian rum — not for the faint-hearted', wiki:'https://en.wikipedia.org/wiki/Stroh_(rum)' },
    usa:{ drink:'Everclear Shot', desc:'Same brutal ABV energy — or sub Bacardi 151 to survive the night', wiki:'https://en.wikipedia.org/wiki/Everclear_(alcohol)' } },
  { g:'J', flag:'🇩🇿', name:'Algeria', abbr:'ALG', conf:'CAF',
    auth:{ drink:'Mahia', desc:'Date or fig brandy from the Maghreb region', wiki:'https://en.wikipedia.org/wiki/Mahia_(drink)' },
    usa:{ drink:'Brandy Shot', desc:'E&J, Paul Masson, or Christian Brothers — fruit brandy is the family', wiki:'https://en.wikipedia.org/wiki/Brandy' } },
  { g:'J', flag:'🇯🇴', name:'Jordan', abbr:'JOR', conf:'AFC',
    auth:{ drink:'Arak', desc:'Levantine anise spirit — first World Cup, big sip', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:'Anise liqueur family — Sambuca is the easiest American bar find', wiki:'https://en.wikipedia.org/wiki/Sambuca' } },
  { g:'K', flag:'🇵🇹', name:'Portugal', abbr:'POR', conf:'UEFA',
    auth:{ drink:'Ginjinha', desc:'Sour cherry liqueur — served in chocolate cups', wiki:'https://en.wikipedia.org/wiki/Ginjinha' },
    usa:{ drink:'Cherry Bounce Shot', desc:'Luxardo Maraschino or Cherry Heering — sour cherry liqueur family', wiki:'https://en.wikipedia.org/wiki/Cherry_Heering' } },
  { g:'K', flag:'🇨🇴', name:'Colombia', abbr:'COL', conf:'CONMEBOL',
    auth:{ drink:'Aguardiente', desc:'Anise-flavored sugarcane spirit — party starter', wiki:'https://en.wikipedia.org/wiki/Aguardiente' },
    usa:{ drink:'Sambuca + Sugar Shot', desc:'Similar anise-sweet profile — or white rum with a drop of anise bitters', wiki:'https://en.wikipedia.org/wiki/Sambuca' } },
  { g:'K', flag:'🇮🇶', name:'Iraq', abbr:'IRQ', conf:'AFC',
    auth:{ drink:'Arak', desc:'Mesopotamian anise spirit — ancient as the rivers', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:'Anise family — same approach, much easier to find', wiki:'https://en.wikipedia.org/wiki/Sambuca' } },
  { g:'K', flag:'🇵🇾', name:'Paraguay', abbr:'PAR', conf:'CONMEBOL',
    auth:{ drink:'Caña', desc:'Paraguayan sugarcane spirit, raw and sweet', wiki:'https://en.wikipedia.org/wiki/Ca%C3%B1a_(liquor)' },
    usa:{ drink:'White Rum Shot', desc:'Unaged sugarcane spirit — Bacardi Silver or Plantation 3 Star', wiki:'https://en.wikipedia.org/wiki/Rum' } },
  { g:'L', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', name:'England', abbr:'ENG', conf:'UEFA',
    auth:{ drink:'London Dry Gin', desc:"Double it up — it's coming home", wiki:'https://en.wikipedia.org/wiki/London_dry_gin' },
    usa:{ drink:'Gin Shot', desc:'Tanqueray or Beefeater — London Dry is at every bar', wiki:'https://en.wikipedia.org/wiki/Gin' } },
  { g:'L', flag:'🇭🇷', name:'Croatia', abbr:'CRO', conf:'UEFA',
    auth:{ drink:'Šljivovica', desc:'Plum brandy — fierce Balkan tradition', wiki:'https://en.wikipedia.org/wiki/Slivovitz' },
    usa:{ drink:'Slivovitz or Brandy', desc:'Eastern European stores carry Slivovitz — otherwise any dark brandy', wiki:'https://en.wikipedia.org/wiki/Slivovitz' } },
  { g:'L', flag:'🇰🇿', name:'Kazakhstan', abbr:'KAZ', conf:'UEFA',
    auth:{ drink:'Kumiss', desc:"Fermented mare's milk — an acquired taste", wiki:'https://en.wikipedia.org/wiki/Kumiss' },
    usa:{ drink:'Kefir + Vodka Shot', desc:"Mix a shot of vodka into plain kefir — as close as you're getting", wiki:'https://en.wikipedia.org/wiki/Kefir' } },
  { g:'L', flag:'🇭🇹', name:'Haiti', abbr:'HTI', conf:'CONCACAF',
    auth:{ drink:'Clairin', desc:"Raw sugarcane spirit — Haiti's wild native rum", wiki:'https://en.wikipedia.org/wiki/Clairin' },
    usa:{ drink:'Overproof White Rum', desc:'Rum Fire or Smith & Cross — funky, raw, high-proof sugarcane spirit', wiki:'https://en.wikipedia.org/wiki/Overproof_rum' } },
]

export const TODAY = '2026-06-20'

export const DAY_LABELS: Record<string, string> = {
  '2026-06-19': 'Thu · Jun 19',
  '2026-06-20': 'Today · Jun 20',
  '2026-06-21': 'Sat · Jun 21',
  '2026-06-22': 'Sun · Jun 22',
  '2026-06-23': 'Mon · Jun 23',
}

export const teamByAbbr = (abbr: string) => TEAMS.find(t => t.abbr === abbr)
